---
image: "ubuntu/latest"
pacakges:
  - rustc
  - cargo
  - libmariadb-dev-compat
tasks:
  - build: |
      cd ~/Clacks
      cargo build
  - test: |
      cd ~/Clacks
      cargo test -- --no-capture
